version: '3'
services:
  database:
    image: "mysql:5.6"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: flowupdb
      MYSQL_USER: flowupUser
      MYSQL_PASSWORD: flowupPassword
    ports:
      - 3306:3306
    expose:
      - 3306
  elasticsearch:
    image: "elasticsearch:2.3"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9200
  grafana:
    image: "grafana/grafana"
    ports:
      - 3000:3000
    expose:
      - 3000
  redis:
    image: "redis:3.2"
    ports:
      - 6379:6379
    expose:
      - 6379
volumes:
    db_data:
    es_data:
